### ISSUE TITLE
!remindme functionality

### ISSUE THREAD

**Issue by sladigar** [MediaButler/MediaButler#140]
## Expected Behavior
!remindme function to provide reminder in 30 days using 43200 minutes. 

## Actual Behavior
!remindme function provided immediate reminder, and I'll forget what I wanted to be reminded of in 30 days, so will not know if it worked or not.

## Steps to Reproduce the Problem

  1. !remindme 999999 test - immediate reminder
  2. !remindme 9999 test2 - no immediate reminder
  3. 35791 does not provide immediate reminder, 35792 does

## Specifications

  - Version: 0.4
  - Platform: all
  - Subsystem:

**Comment by vertig0ne** [comment]
Issue Confirmed
