### ISSUE TITLE
Certain commands do not work

### ISSUE THREAD

**Issue by samwiseg00** [MediaButler/MediaButler#148]
## Expected Behavior
stuff should work? :)

## Actual Behavior
![image](https://user-images.githubusercontent.com/2241731/36879223-bd3bc310-1d90-11e8-936a-8822a16741a0.png)
invalid image top left 

!stats history username 
   is case sensitive... can this be normalized?

!movie add Test (2013)
   results in ERR: Error

!tv tonight
   results "Querying Tonight from Sonarr" but nothing returns

!tv add House
   results in ERR: Error

## Steps to Reproduce the Problem

  1. run in docker
  1. config
  1. run commands

## Specifications

  - Version: 0.4-14f5a9b18ca848186daa9d3860ade5eeaccc07e7
  - Platform: Docker
  - Subsystem: Centos 7

**Comment by rob1998** [comment]
I also get an error with "!tv tonight", same for "!tv add House" and "!movie add Test" this shows up in the console:
```
(node:67672) UnhandledPromiseRejectionWarning: Error
    at promiseRequest.then.catch.e (MediaButler\node_modules\sonarr-api\lib\api.js:189:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:67672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The invalid image is an easy fix

**Comment by vertig0ne** [comment]
These issues should now be resolved, please update your docker, possibly reconfigure and retest

**Comment by samwiseg00** [comment]
Sure... already did it last night with you guys... you can close this one :)
